apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-resource-limits
  annotations:
    policies.kyverno.io/title: Require Resource Limits
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Resource limits control the maximum amount of CPU and memory that a
      container can use. This policy ensures that all containers have CPU
      and memory limits defined to prevent resource exhaustion.
spec:
  validationFailureAction: enforce
  background: true
  rules:
    - name: check-container-resources
      match:
        any:
        - resources:
            kinds:
              - Pod
      validate:
        message: >-
          All containers must have CPU and memory limits defined.
          Please add resources.limits.cpu and resources.limits.memory.
        pattern:
          spec:
            containers:
              - resources:
                  limits:
                    memory: "?*"
                    cpu: "?*"
                  requests:
                    memory: "?*"
                    cpu: "?*"
    - name: check-init-container-resources
      match:
        any:
        - resources:
            kinds:
              - Pod
      preconditions:
        all:
        - key: "{{ request.object.spec.initContainers[] | length(@) }}"
          operator: GreaterThan
          value: 0
      validate:
        message: >-
          All init containers must have CPU and memory limits defined.
        pattern:
          spec:
            initContainers:
              - resources:
                  limits:
                    memory: "?*"
                    cpu: "?*"
                  requests:
                    memory: "?*"
                    cpu: "?*"
