# Jenkins Configuration as Code (JCasC)

# This file configures Jenkins system settings, credentials, and security
# Place this in $JENKINS_HOME/jenkins.yaml for automatic configuration

# System Configuration
jenkins:
  systemMessage: "Jenkins CI/CD Pipeline - AWS EKS Deployment"
  
  # Security settings
  securityRealm:
    saml:
      binding: "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
      displayNameAttributeName: "name"
      groupsAttributeName: "groups"
      idpMetadataConfiguration:
        url: "https://your-idp-metadata-url"
      logoutUrl: "https://your-idp-logout-url"
      usernameAttributeName: "email"

  # Authentication
  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            permissions:
              - "hudson.model.Hudson.Administer"
              - "hudson.model.Hudson.ConfigureUpdateCenter"
              - "hudson.model.Hudson.RunScripts"
              - "hudson.model.Hudson.UploadPlugins"
              - "hudson.model.View.Create"
              - "hudson.model.View.Delete"
              - "hudson.model.View.Configure"
              - "hudson.scm.SCM.ExtensionPoint"
          
          - name: "developer"
            permissions:
              - "hudson.model.Item.Build"
              - "hudson.model.Item.Cancel"
              - "hudson.model.Item.Discover"
              - "hudson.model.Item.Move"
              - "hudson.model.Item.Read"
              - "hudson.model.Run.Delete"
              - "hudson.model.Run.Update"
              - "hudson.model.View.Configure"
              - "hudson.model.View.Create"
              - "hudson.model.View.Read"
          
          - name: "viewer"
            permissions:
              - "hudson.model.Item.Discover"
              - "hudson.model.Item.Read"
              - "hudson.model.Run.Replay"
              - "hudson.model.View.Read"

  # Disable script approval for trusted admins
  scriptApproval:
    # Approved scripts go here
    hash: ""

  # Configure update center
  updateCenter:
    sites:
      - id: "default"
        url: "https://updates.jenkins.io/update-center.json"

# Credentials Configuration
credentials:
  system:
    domainCredentials:
      - credentials:
          - aws:
              scope: GLOBAL
              id: "aws-credentials"
              description: "AWS Access Credentials for EKS and ECR"
              accessKey: "${AWS_ACCESS_KEY_ID}"
              secretKey: "${AWS_SECRET_ACCESS_KEY}"

          - string:
              scope: GLOBAL
              id: "aws-account-id"
              secret: "${AWS_ACCOUNT_ID}"
              description: "AWS Account ID"

          - basicSSHUserPrivateKey:
              scope: GLOBAL
              id: "git-ssh-key"
              description: "SSH key for Git operations"
              username: "jenkins"
              privateKeySource:
                directEntry:
                  privateKey: "${GIT_SSH_KEY}"

          - usernamePassword:
              scope: GLOBAL
              id: "git-credentials"
              username: "${GIT_USERNAME}"
              password: "${GIT_PASSWORD}"
              description: "GitHub credentials for HTTPS access"

          - string:
              scope: GLOBAL
              id: "snyk-api-token"
              secret: "${SNYK_TOKEN}"
              description: "Snyk API Token for security scanning"

          - string:
              scope: GLOBAL
              id: "argocd-token"
              secret: "${ARGOCD_TOKEN}"
              description: "ArgoCD authentication token"

          - string:
              scope: GLOBAL
              id: "argocd-server"
              secret: "${ARGOCD_SERVER}"
              description: "ArgoCD server URL"

# Tool Configuration
tool:
  # Git configuration
  git:
    installations:
      - name: "Default"
        home: "git"
        
  # Maven configuration
  maven:
    installations:
      - name: "Maven 3.8.1"
        home: "/usr/share/maven"
        
  # Java configuration
  jdk:
    installations:
      - name: "Java 11"
        home: "/usr/lib/jvm/java-11-openjdk"

# Kubernetes Cloud Configuration
clouds:
  - kubernetes:
      name: "EKS-Cluster"
      serverUrl: "${KUBERNETES_URL}"
      serverCertificate: "${KUBERNETES_CERT}"
      credentialsId: "kubernetes-credentials"
      skipTlsVerify: false
      namespace: "jenkins"
      jenkinsUrl: "http://jenkins.jenkins.svc.cluster.local:8080"
      jenkinsTunnel: "jenkins-agent.jenkins.svc.cluster.local:50000"
      containerCapStr: 100
      connectTimeout: 5
      readTimeout: 15
      maxRequestsPerHostStr: 32
      retentionTimeout: 5
      waitForPodSec: 600
      
      templates:
        - name: "docker-agent"
          namespace: "jenkins"
          labels: "docker agent"
          instanceCap: 10
          idleMinutes: 5
          activeDeadlineSeconds: 3600
          
          containers:
            - name: "docker"
              image: "docker:20-dind"
              alwaysPullImage: true
              workingDir: "/home/jenkins"
              resourceRequestCpu: "500m"
              resourceRequestMemory: "512Mi"
              resourceLimitCpu: "2000m"
              resourceLimitMemory: "2Gi"
              ttyEnabled: true
              envVars:
                - envVar:
                    key: "DOCKER_HOST"
                    value: "unix:///var/run/docker.sock"
              
            - name: "jnlp"
              image: "jenkins/inbound-agent:latest-jdk11"
              workingDir: "/home/jenkins"
              resourceRequestCpu: "500m"
              resourceRequestMemory: "512Mi"
              resourceLimitCpu: "2000m"
              resourceLimitMemory: "2Gi"
              
          nodeSelector: "jenkins=true"
          serviceAccount: "jenkins"
          automountServiceAccountToken: true

# System Messages and Groovy Hooks
unclassified:
  # Configure Email notifications
  mailer:
    smtpHost: "${SMTP_HOST}"
    smtpPort: 587
    useSMTPAuth: true
    smtpAuthUsername: "${SMTP_USERNAME}"
    smtpAuthPassword: "${SMTP_PASSWORD}"
    charset: "UTF-8"
    
  # Location configuration
  location:
    url: "${JENKINS_URL}"
    
  # AWS configuration
  awsconfig:
    region: "us-east-1"
    useInstanceProfile: true
    credentialsId: "aws-credentials"
    
  # GitHub configuration
  gitHub:
    apiUrl: "https://api.github.com"
    credentialsId: "git-credentials"
    
  # Slack configuration (optional)
  slackNotifier:
    teamDomain: "${SLACK_TEAM}"
    token: "${SLACK_TOKEN}"
    tokenCredentialId: "slack-token"
    botUser: false
    sendAsBot: true
    roomIdResolver: "default"
    
  # Blue Ocean configuration
  blueOcean:
    dashboardTabs:
      - id: "dashboard"
        displayName: "Dashboard"
    endpoints:
      - displayName: "GitHub"
        iconClassName: "icon-github-circle"
        url: "https://github.com"

# Job-related configuration
jobs:
  - script: >
      pipelineJob('cicd-pipeline') {
        definition {
          cps {
            script(readFileFromWorkspace('Jenkinsfile'))
            sandbox(true)
          }
        }
        triggers {
          githubPush()
        }
      }

# Configure global pipeline libraries
globalLibraries:
  libraries:
    - name: "shared-pipeline-library"
      defaultVersion: "main"
      implicit: true
      allowVersionOverride: true
      includeInChangesets: false
      scm:
        git:
          remote: "${SHARED_LIBRARY_REPO}"
          credentialsId: "git-credentials"

# Security configuration
unclassified:
  awsCodePipeline:
    proxyHost: ""
    proxyPort: 0
    region: "us-east-1"
    credentialsId: "aws-credentials"
    
  timestamper:
    allPipelines: true
    elapsedTimeFormat: "'['HH:mm:ss.S']' "
    systemTimeFormat: "'['yyyy-MM-dd HH:mm:ss Z']' "
