#!/bin/bash
set -e

ENVIRONMENT=$1
HELM_CHART_VERSION=$2
IMAGE_TAG=$3

if [ -z "$ENVIRONMENT" ] || [ -z "$HELM_CHART_VERSION" ] || [ -z "$IMAGE_TAG" ]; then
    echo "Usage: $0 <environment> <helm_chart_version> <image_tag>"
    exit 1
fi

echo "========================================="
echo "Stage 6: Updating Config Repository"
echo "========================================="
echo "Environment: $ENVIRONMENT"
echo "Helm Chart Version: $HELM_CHART_VERSION"
echo "Image Tag: $IMAGE_TAG"
echo "========================================="

# Clone the config repository (GitOps repo for ArgoCD)
CONFIG_REPO_URL="${CONFIG_REPO_URL:-git@gitlab.com:your-org/config-repo.git}"
CONFIG_REPO_DIR="/tmp/config-repo"

echo "Cloning config repository..."
rm -rf $CONFIG_REPO_DIR
git clone $CONFIG_REPO_URL $CONFIG_REPO_DIR
cd $CONFIG_REPO_DIR

# Create or update config.yaml for the environment
CONFIG_FILE="environments/${ENVIRONMENT}/config.yaml"
mkdir -p "environments/${ENVIRONMENT}"

cat > $CONFIG_FILE <<EOF
# Auto-generated by CI/CD Pipeline
# Date: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
# Commit: ${CI_COMMIT_SHORT_SHA}
# Pipeline: ${CI_PIPELINE_URL}

application:
  name: ${CI_PROJECT_NAME}
  environment: ${ENVIRONMENT}

helm:
  chart:
    repository: oci://${AWS_ECR_REGISTRY}/helm-charts
    name: ${CI_PROJECT_NAME}
    version: ${HELM_CHART_VERSION}
  
  values:
    image:
      repository: ${AWS_ECR_REGISTRY}/${CI_PROJECT_NAME}
      tag: ${IMAGE_TAG}
    
    replicaCount: 2
    
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi

terraform:
  version: "1.6.0"
  
deployment:
  timestamp: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
  triggeredBy: ${GITLAB_USER_LOGIN}
  commitSha: ${CI_COMMIT_SHA}
  branch: ${CI_COMMIT_REF_NAME}
EOF

echo "✅ Created config file: $CONFIG_FILE"
cat $CONFIG_FILE

# Commit and push changes
echo ""
echo "Committing changes to config repository..."
git add $CONFIG_FILE
git commit -m "Update ${ENVIRONMENT} config - Helm: ${HELM_CHART_VERSION}, Image: ${IMAGE_TAG}

Triggered by: ${GITLAB_USER_LOGIN}
Pipeline: ${CI_PIPELINE_URL}
Commit: ${CI_COMMIT_SHA}"

git push origin main

echo ""
echo "========================================="
echo "✅ Config repository updated successfully"
echo "ArgoCD will detect changes and deploy to ${ENVIRONMENT}"
echo "========================================="
